INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('Andres','Gonzalez','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('Olga','Rodriguez','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('Manolo','f','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('Luis','r','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('jose','Gonzalez','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('felipe','Rodriguez','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('Antonio','f','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('Javier','r','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('paco','Gonzalez','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('nico','Rodriguez','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('simon','f','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('hugo','r','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('lucas','Gonzalez','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('pedro','Rodriguez','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('luis','f','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('tito','r','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('ana','r','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('david','Gonzalez','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('juan','Rodriguez','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('sahi','f','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('nani','r','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('luci','Gonzalez','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('viada','Rodriguez','mailol@gamil.com','2018-08-18','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('tote','f','mail1@gamil.com','2019-08-28','');
INSERT INTO clientes (nombre,apellido,email,create_at,foto) VALUES ('victor','r','mailol@gamil.com','2018-08-18','');

INSERT INTO productos (nombre,precio,create_at) VALUES ('P1',25.3,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P2',25369,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P3',258479,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P4',100,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P5',150,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P6',200,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P7',250,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P8',50,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P9',10.5,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P10',20000,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('P11',360,NOW());

INSERT INTO facturas (descripcion,observacion,cliente_id,create_at) VALUES ('F1','Factura 1',1,NOW());
INSERT INTO facturas_items (cantidad,factura_id,producto_id) VALUES (1,1,1);
INSERT INTO facturas_items (cantidad,factura_id,producto_id) VALUES (2,1,4);
INSERT INTO facturas_items (cantidad,factura_id,producto_id) VALUES (1,1,5);
INSERT INTO facturas_items (cantidad,factura_id,producto_id) VALUES (1,1,7);

INSERT INTO facturas (descripcion,observacion,cliente_id,create_at) VALUES ('F2','Factura 2',1,NOW());
INSERT INTO facturas_items (cantidad,factura_id,producto_id) VALUES (3,2,6);